on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
        default: "nobody"

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "create 4 ${{ github.event.inputs.name }}!"

  delete:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "delete 4 ${{ github.event.inputs.name }}!"    
     